import { useEffect, useState, type ComponentType, type ReactNode } from "react";
import {
  Activity, BarChart3, Bell, BookMarked, BookOpen, Bot, Braces, Check, ChevronLeft,
  ChevronRight, CircleAlert, Clock3, Code2, Copy, Database, Eye, Filter, Gauge,
  GitCompareArrows, Globe2, Layers3, Link2, Maximize2, Menu, Network, RefreshCw,
  Save, Search, Settings2, ShieldCheck, Sparkles, Square, TestTube2, TrendingUp,
  TriangleAlert, Wifi, X,
} from "lucide-react";
import {
  Area, AreaChart, Bar, BarChart, CartesianGrid, Line, ResponsiveContainer,
  Tooltip, XAxis, YAxis,
} from "recharts";
import "./luxalgo-premium.css";
import "./luxalgo-premium-sections.css";

type Json = Record<string, any>;
type Tab = "OVERVIEW" | "LIBRARY" | "PRICE ACTION" | "MARKET STRUCTURE" | "LIQUIDITY" | "SUPPORT & RESISTANCE" | "FVG / IMBALANCE" | "ORDER BLOCKS" | "INDICATORS" | "SOURCE CODE" | "EDGE STATS" | "SAVED RESEARCH" | "SYNC STATUS" | "SETTINGS";
type IconType = ComponentType<{ size?: number; className?: string }>;

export type LuxPremiumModel = {
  tab: Tab; setTab: (tab: Tab) => void; onBack: () => void; onAskMaster: (prompt?: string) => void;
  status: string; loading: boolean; error: string; setError: (value: string) => void;
  overview: Json | null; health: Json | null; sync: Json | null; database: Json;
  results: Json[]; families: Json[]; tags: Json[]; selected: Json | null; selectedType: "concept" | "indicator" | null;
  setSelected: (value: Json | null) => void; query: string; setQuery: (value: string) => void;
  family: string; setFamily: (value: string) => void; tag: string; setTag: (value: string) => void;
  kind: "concepts" | "indicators"; setKind: (value: "concepts" | "indicators") => void;
  sourceOnly: boolean; setSourceOnly: (value: boolean) => void; savedOnly: boolean; setSavedOnly: (value: boolean) => void;
  platform: string; setPlatform: (value: string) => void; tier: string; setTier: (value: string) => void;
  sort: string; setSort: (value: string) => void; page: number; hasMore: boolean;
  source: Json | null; sourceSearch: string; setSourceSearch: (value: string) => void;
  sourceFullscreen: boolean; setSourceFullscreen: (value: boolean | ((value: boolean) => boolean)) => void;
  saved: Json[]; history: Json[]; edge: Json; settings: Json; syncCounters: Json; syncRunning: boolean;
  code: string; codeLines: string[]; matchingLines: number;
  importedCount: (databaseKey: string, counterKey: string) => number;
  search: (term?: string, type?: "all" | "concepts" | "indicators", move?: boolean) => Promise<void>;
  browse: (page?: number, type?: "concepts" | "indicators") => Promise<void>;
  openItem: (item: Json) => Promise<void>; saveItem: (item: Json, type?: "concept" | "indicator" | null) => Promise<void>;
  loadSource: (slug: string) => Promise<void>; compare: () => Promise<void>; updateSettings: (next: Json) => Promise<void>;
  loadShell: () => Promise<void>; startSync: (mode: "FULL" | "CHANGES") => Promise<void>;
  resumeSync: () => Promise<void>; retrySync: () => Promise<void>; cancelSync: () => Promise<void>;
  edgeReport: (preset: string, symbol: string) => Promise<void>;
  removeSaved: (id: string) => Promise<void>;
};

const quick = ["Liquidity Sweep", "BOS", "CHoCH", "Fair Value Gap", "Order Block", "ATR"];
const researchTabs: Array<{ tab: Tab; label: string; icon: IconType }> = [
  { tab: "OVERVIEW", label: "Overview", icon: Gauge }, { tab: "LIBRARY", label: "Library", icon: BookOpen },
  { tab: "PRICE ACTION", label: "Price Action", icon: TrendingUp }, { tab: "INDICATORS", label: "Indicators", icon: BarChart3 },
  { tab: "SOURCE CODE", label: "Source Code", icon: Code2 }, { tab: "EDGE STATS", label: "Edge Stats", icon: Activity },
  { tab: "SAVED RESEARCH", label: "Saved Research", icon: BookMarked }, { tab: "SYNC STATUS", label: "Sync Status", icon: RefreshCw },
  { tab: "SETTINGS", label: "Connections", icon: Settings2 },
];
const categories: Array<{ tab: Tab; label: string; subtitle: string; icon: IconType }> = [
  { tab: "LIQUIDITY", label: "Liquidity", subtitle: "Sweeps, pools and resting orders", icon: Activity },
  { tab: "MARKET STRUCTURE", label: "Market Structure", subtitle: "BOS, CHoCH, MSS and swings", icon: TrendingUp },
  { tab: "FVG / IMBALANCE", label: "FVG / Imbalance", subtitle: "Fair value gaps and inefficiencies", icon: Layers3 },
  { tab: "ORDER BLOCKS", label: "Order Blocks", subtitle: "Institutional order flow", icon: Database },
  { tab: "PRICE ACTION", label: "Breakouts", subtitle: "Range, structure and volatility", icon: BarChart3 },
  { tab: "PRICE ACTION", label: "Fakeouts", subtitle: "Traps and liquidity raids", icon: GitCompareArrows },
  { tab: "PRICE ACTION", label: "Pullbacks", subtitle: "Optimal entries and continuation", icon: TrendingUp },
  { tab: "SUPPORT & RESISTANCE", label: "Support / Resistance", subtitle: "Key levels and confluence", icon: ShieldCheck },
];
const spark = [28, 36, 31, 48, 44, 61, 54, 76, 68, 86].map((value, index) => ({ index, value }));
const sessionFallback: Json[] = [];
const cx = (...values: Array<string | false | null | undefined>) => values.filter(Boolean).join(" ");
const array = (value: unknown): Json[] => Array.isArray(value) ? value : [];
const number = (value: unknown) => Number.isFinite(Number(value)) ? Number(value) : 0;
const date = (value: unknown) => value ? new Date(String(value)).toLocaleString() : "Not available";
const itemType = (item: Json) => item.kind === "indicator" || item.source_code_available !== undefined || item.item_type === "INDICATOR" ? "indicator" : "concept";
const description = (item: Json) => item.short_description || item.description || item.snapshot?.short_description || item.snapshot?.description || "Open the synchronized LuxAlgo record for available research details.";

function StatusPill({ tone = "blue", icon: Icon = Wifi, children }: { tone?: string; icon?: IconType; children: ReactNode }) {
  return <span className={`luxp-status ${tone}`}><Icon size={14} /><span>{children}</span></span>;
}
function Metric({ icon: Icon, value, label, helper, tone = "blue" }: { icon: IconType; value: ReactNode; label: string; helper?: string; tone?: string }) {
  return <article className={`luxp-metric ${tone}`}><span className="luxp-icon"><Icon size={22} /></span><div><strong>{value}</strong><b>{label}</b>{helper && <small>{helper}</small>}</div></article>;
}
function Panel({ title, eyebrow, icon: Icon, action, className, children }: { title: string; eyebrow?: string; icon?: IconType; action?: ReactNode; className?: string; children: ReactNode }) {
  return <section className={cx("luxp-panel", className)}><header><div>{eyebrow && <span>{eyebrow}</span>}<h2>{Icon && <Icon size={19} />}{title}</h2></div>{action}</header>{children}</section>;
}
function Sparkline({ color = "#1fa5ff" }: { color?: string }) {
  return <div className="luxp-spark"><ResponsiveContainer width="100%" height="100%"><AreaChart data={spark}><defs><linearGradient id={`spark-${color.replace("#", "")}`} x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor={color} stopOpacity={.34}/><stop offset="100%" stopColor={color} stopOpacity={0}/></linearGradient></defs><Area type="monotone" dataKey="value" stroke={color} fill={`url(#spark-${color.replace("#", "")})`} strokeWidth={2} isAnimationActive={false}/></AreaChart></ResponsiveContainer></div>;
}
function EmptyState({ title, body, icon: Icon = Database }: { title: string; body: string; icon?: IconType }) {
  return <div className="luxp-empty"><Icon size={28}/><strong>{title}</strong><p>{body}</p></div>;
}
function ResultCard({ item, model }: { item: Json; model: LuxPremiumModel }) {
  const type = itemType(item);
  return <article className="luxp-result-card"><div className="luxp-result-chart"><Sparkline color={type === "indicator" ? "#4fe5be" : "#199cff"}/></div><div className="luxp-result-copy"><span>{item.family || (type === "indicator" ? "Indicator" : "Concept")}</span><h3>{item.name || item.slug}</h3><p>{description(item)}</p><footer><small>{array(item.relationships).length} linked records</small><button onClick={() => void model.saveItem(item, type)} aria-label="Save research"><Save size={15}/></button><button onClick={() => void model.openItem(item)}>View Details <ChevronRight size={14}/></button></footer></div></article>;
}
function ResearchDetail({ model, full = false, onClose }: { model: LuxPremiumModel; full?: boolean; onClose?: () => void }) {
  const item = model.selected;
  if (!item) return <EmptyState title="Choose a research item" body="Select a concept or indicator to open its synchronized LuxAlgo details."/>;
  const tags = array(item.tags).map((tag) => typeof tag === "string" ? tag : tag.name || tag.id).filter(Boolean);
  const text = String(item.content_markdown || item.body_markdown || item.description || "");
  const paragraphs = text.split(/\n\s*\n/).filter(Boolean);
  const relation = array(item.relationships);
  return <div className={cx("luxp-detail", full && "full")}>
    <div className="luxp-detail-title"><span className="luxp-icon"><BookOpen size={22}/></span><div><small>LUXALGO {model.selectedType?.toUpperCase() || "RESEARCH"}</small><h2>{item.name || item.slug}</h2><p>{description(item)}</p></div>{onClose && <button onClick={onClose}><X size={18}/></button>}</div>
    <div className="luxp-chips">{[item.family, ...tags].filter(Boolean).slice(0, 7).map((tag) => <span key={String(tag)}>{String(tag)}</span>)}</div>
    <div className="luxp-chart-hero"><img src="/trade-setup-breakout.png" alt="OnkarTradeX market structure research chart"/></div>
    <div className="luxp-detail-sections"><article><h3>Definition</h3><p>{paragraphs[0] || description(item)}</p></article><article><h3>How It Works</h3><p>{paragraphs[1] || "The imported MCP record does not include a separate methodology section."}</p></article></div>
    <dl className="luxp-meta"><div><dt>Source</dt><dd>{item.attribution || "LuxAlgo"}</dd></div><div><dt>Family</dt><dd>{item.family || "Not supplied"}</dd></div><div><dt>Last Synced</dt><dd>{date(item.last_synced_at)}</dd></div><div><dt>Related</dt><dd>{relation.length} records</dd></div></dl>
    <div className="luxp-actions"><button className="primary" onClick={() => void model.saveItem(item)}><Save size={16}/> Save Research</button>{model.selectedType === "concept" && <button onClick={() => void model.compare()}><GitCompareArrows size={16}/> Compare with Onkar Rules</button>}{model.selectedType === "indicator" && item.source_code_available && <button onClick={() => void model.loadSource(item.slug)}><Code2 size={16}/> View Source</button>}<button className="violet" onClick={() => model.onAskMaster(`Use this LUXALGO_REFERENCE for research only: ${item.name || item.slug}`)}><Sparkles size={16}/> Ask Master AI</button></div>
    {item.comparison && <Comparison data={item.comparison}/>}
  </div>;
}
function Comparison({ data }: { data?: Json }) {
  const rows = array(data?.comparisons);
  return <div className="luxp-comparison"><header><h3><GitCompareArrows size={18}/> Compare with Onkar Rules</h3></header>{rows.length ? rows.slice(0, 2).map((row) => <article key={row.id || row.name}><div><small>ONKAR SETUP</small><strong>{row.name}</strong><p>{row.note}</p></div><div><small>MATCHING CONDITIONS</small><p>{array(row.commonTerms).join(", ") || "No strong textual overlap found."}</p></div></article>) : <p>Run a comparison to map this research concept against approved Onkar setup rules. LuxAlgo never modifies execution rules.</p>}</div>;
}

function Overview({ model }: { model: LuxPremiumModel }) {
  const recent = model.history.slice(0, 4);
  return <div className="luxp-stack">
    <div className="luxp-metrics six"><Metric icon={BookOpen} value={model.importedCount("concepts", "conceptsListed")} label="Trading Concepts" helper="Explore market concepts" tone="cyan"/><Metric icon={TrendingUp} value={model.importedCount("indicators", "indicatorsListed")} label="Indicators" helper="Built for all markets"/><Metric icon={Layers3} value={model.importedCount("families", "families")} label="Families" helper="Organized research" tone="violet"/><Metric icon={BookMarked} value={model.saved.length} label="Saved Research" helper="Your collection" tone="violet"/><Metric icon={Code2} value={model.importedCount("sourceFiles", "sourceFiles")} label="Source Code" helper="Public references"/><Metric icon={Activity} value={model.edge.presets?.length || "—"} label="Edge Stats" helper="Historical context" tone="cyan"/></div>
    <div className="luxp-overview-main"><Panel title="Search LuxAlgo Research" icon={Search} className="luxp-search-panel"><form onSubmit={(event) => { event.preventDefault(); void model.search(model.query); }}><Search size={18}/><input value={model.query} onChange={(event) => model.setQuery(event.target.value)} placeholder="Search concepts, indicators, liquidity, FVG, BOS…"/><button><ChevronRight/></button></form><div className="luxp-quick"><span>Quick Search:</span>{quick.map((item) => <button key={item} onClick={() => { model.setQuery(item); void model.search(item); }}>{item}</button>)}</div></Panel><aside className="luxp-hero"><div><strong>Institutional Knowledge.</strong><b>Now at Your Fingertips.</b><ul><li><Check/> Real Concepts</li><li><Check/> Real Indicators</li><li><Check/> Powered by LuxAlgo MCP</li></ul></div><img src="/onkar-tradex-lockup.webp" alt="OnkarTradeX research"/></aside></div>
    <div className="luxp-dashboard-grid"><Panel title="Recent Research" icon={Clock3} action={<button onClick={() => model.setTab("SAVED RESEARCH")}>View All <ChevronRight size={14}/></button>}><div className="luxp-recent">{recent.length ? recent.map((row, index) => <button key={row.id || index} onClick={() => { model.setQuery(row.query); void model.search(row.query); }}><Sparkline/><span><strong>{row.query}</strong><small>LuxAlgo research search</small></span><time>{date(row.created_at)}</time></button>) : <EmptyState title="No recent research" body="Your LuxAlgo searches will appear here." icon={Clock3}/>}</div></Panel><Panel title="LuxAlgo MCP Health" icon={Activity} action={<StatusPill tone={model.status === "CONNECTED" ? "green" : "red"}>{model.status}</StatusPill>}><dl className="luxp-health-list"><div><dt>Status</dt><dd>{model.status}</dd></div><div><dt>Endpoint</dt><dd>mcp.luxalgo.com/mcp</dd></div><div><dt>Available Tools</dt><dd>{model.health?.availableTools?.length ?? model.health?.available_tools ?? "—"}</dd></div><div><dt>Last Success</dt><dd>{date(model.health?.lastSuccessfulRequest || model.health?.last_successful_request)}</dd></div></dl><div className="luxp-activity"><BarChart3 size={18}/><span>Research Activity</span><div>{[22,30,28,44,38,51,47,62,44,35,41,56].map((height, index) => <i key={index} style={{ height: `${height}%` }}/>)}</div></div></Panel><div className="luxp-side-stack"><Panel title="Compare with Onkar Rules" icon={GitCompareArrows}><Comparison data={model.selected?.comparison}/></Panel><Panel title="Master AI Research Access" icon={Bot}><div className="luxp-agents">{[["Master AI", model.settings.allow_master_ai],["Trend AI", model.settings.allow_trend_ai],["Zone AI", model.settings.allow_zone_ai],["Setup AI", model.settings.allow_setup_ai]].map(([name, enabled]) => <span key={String(name)}><Bot size={17}/><b>{name}</b><small className={enabled !== false ? "on" : "off"}>{enabled !== false ? "Enabled" : "Blocked"}</small></span>)}</div></Panel></div></div>
  </div>;
}

function Library({ model, indicator = false }: { model: LuxPremiumModel; indicator?: boolean }) {
  const [fullDetail, setFullDetail] = useState(false);
  useEffect(() => { setFullDetail(false); }, [model.selected?.slug]);
  if (fullDetail && model.selected) return <ConceptPage model={model} onBack={() => setFullDetail(false)}/>;
  return <div className={cx("luxp-library-layout", model.selected && "with-detail")}>
    <aside className="luxp-family-rail"><h3><Layers3 size={18}/> {indicator ? "Indicator Families" : "Families"}</h3><button className={!model.family ? "active" : ""} onClick={() => { model.setFamily(""); void model.browse(0, indicator ? "indicators" : "concepts"); }}><span>{indicator ? "All Indicators" : "All Concepts"}</span><b>{indicator ? model.importedCount("indicators", "indicatorsListed") : model.importedCount("concepts", "conceptsListed")}</b></button>{model.families.slice(0, 10).map((row) => <button key={row.key} className={model.family === row.key ? "active" : ""} onClick={() => { model.setFamily(row.key); void model.browse(0, indicator ? "indicators" : "concepts"); }}><span>{row.name}</span><b>{row.concept_count || ""}</b></button>)}</aside>
    <main className="luxp-library-main"><form className="luxp-filter-search" onSubmit={(event) => { event.preventDefault(); void model.search(model.query, indicator ? "indicators" : "concepts"); }}><Search size={18}/><input value={model.query} onChange={(event) => model.setQuery(event.target.value)} placeholder={indicator ? "Search indicators…" : "Search concepts, indicators, or tags…"}/><button>Search</button></form><div className="luxp-filterbar"><label>Family<select value={model.family} onChange={(event) => model.setFamily(event.target.value)}><option value="">All Families</option>{model.families.map((row) => <option key={row.key} value={row.key}>{row.name}</option>)}</select></label><label>Tags<select value={model.tag} onChange={(event) => model.setTag(event.target.value)}><option value="">All Tags</option>{model.tags.map((row) => <option key={row.id} value={row.id}>{row.name}</option>)}</select></label>{indicator && <label>Platform<input value={model.platform} onChange={(event) => model.setPlatform(event.target.value)} placeholder="All Platforms"/></label>}<label className="check"><input type="checkbox" checked={model.sourceOnly} onChange={(event) => model.setSourceOnly(event.target.checked)}/> Source Code</label><label className="check"><input type="checkbox" checked={model.savedOnly} onChange={(event) => model.setSavedOnly(event.target.checked)}/> Saved Only</label><button onClick={() => void model.browse(0, indicator ? "indicators" : "concepts")}><Filter size={15}/> Apply</button></div>
      {indicator ? <IndicatorTable model={model}/> : <div className="luxp-result-grid">{model.results.map((item) => <ResultCard key={item.slug} item={item} model={model}/>)}</div>}
      {!model.results.length && <EmptyState title="No imported research matches" body="Change the filters or resume the LuxAlgo Library sync."/>}<div className="luxp-pagination"><button disabled={model.page === 0} onClick={() => void model.browse(model.page - 1, indicator ? "indicators" : "concepts")}><ChevronLeft/> Previous</button><span>Page {model.page + 1}</span><button disabled={!model.hasMore} onClick={() => void model.browse(model.page + 1, indicator ? "indicators" : "concepts")}>Next <ChevronRight/></button></div>
    </main>{model.selected && <aside className="luxp-side-detail"><ResearchDetail model={model} onClose={() => model.setSelected(null)}/><button className="luxp-full-detail" onClick={() => setFullDetail(true)}><Eye size={16}/> Open Full Research</button></aside>}
  </div>;
}
function IndicatorTable({ model }: { model: LuxPremiumModel }) {
  return <div className="luxp-table"><div className="head"><span>Indicator Name</span><span>Family</span><span>Linked Concepts</span><span>Source Code</span><span>Actions</span></div>{model.results.map((item) => <div className={model.selected?.slug === item.slug ? "selected" : ""} key={item.slug}><span className="name"><i><BarChart3 size={18}/></i><b>{item.name || item.slug}</b><small>{description(item)}</small></span><span><em>{item.family || "Library"}</em></span><span className="chips">{array(item.relationships).slice(0, 2).map((row, index) => <small key={row.id || index}>{row.target_id || row.name}</small>)}</span><span><StatusPill tone={item.source_code_available ? "green" : "red"} icon={Code2}>{item.source_code_available ? "Available" : "Unavailable"}</StatusPill></span><span><button onClick={() => void model.openItem(item)}>View Details <ChevronRight size={14}/></button></span></div>)}</div>;
}

function PriceAction({ model }: { model: LuxPremiumModel }) {
  return <div className="luxp-stack"><div className="luxp-category-row">{categories.map(({ tab, label, subtitle, icon: Icon }, index) => <button key={`${label}-${index}`} className={model.tab === tab ? "active" : ""} onClick={() => { model.setTab(tab); model.setQuery(label); void model.search(label, "concepts", false); }}><Icon size={24}/><strong>{label}</strong><small>{subtitle}</small></button>)}</div><div className="luxp-map-grid"><Panel title="Price Action Research Map" icon={Network} className="luxp-map"><div className="luxp-map-canvas"><button className="center" onClick={() => { model.setQuery("market structure"); void model.search("market structure"); }}><TrendingUp/><strong>Market Structure</strong><small>The foundation</small></button>{categories.slice(0, 8).map(({ label, icon: Icon }, index) => <button className={`node n${index + 1}`} key={label} onClick={() => { model.setQuery(label); void model.search(label); }}><Icon size={17}/><strong>{label}</strong></button>)}</div></Panel><Panel title="Research Drilldown" icon={BookOpen}><h3 className="luxp-drill-title">{model.tab === "PRICE ACTION" ? "Market Structure" : model.tab}</h3><p>Open synchronized LuxAlgo records to study definitions, indicators, and related concepts.</p><div className="luxp-topic-list">{["BOS", "CHoCH", "MSS", "Swing Highs", "Swing Lows"].map((topic) => <button key={topic} onClick={() => { model.setQuery(topic); void model.search(topic); }}><TrendingUp size={15}/><b>{topic}</b><ChevronRight size={14}/></button>)}</div></Panel></div><Panel title="Popular Research Paths" icon={Network}><div className="luxp-paths">{[["Liquidity Sweep + FVG","Liquidity"],["BOS + Retest","Market Structure"],["Fakeout at S/R","Fakeout"],["Displacement into OB","Order Blocks"]].map(([title, term]) => <button key={title} onClick={() => { model.setQuery(term); void model.search(term); }}><img src="/trade-setup-breakout.png" alt="Market research path"/><strong>{title}</strong><small>Open synchronized concepts</small></button>)}</div></Panel></div>;
}

function ConceptPage({ model, onBack }: { model: LuxPremiumModel; onBack: () => void }) {
  return <div className="luxp-concept-page"><button className="luxp-back" onClick={onBack}><ChevronLeft/> Back to Library</button><div className="luxp-concept-grid"><main><ResearchDetail model={model} full/><div className="luxp-example-grid"><Panel title="Bullish Example — Sweep Below Support" icon={TrendingUp}><img className="luxp-example-chart" src="/trade-setup-breakout.png" alt="Bullish LuxAlgo concept research example"/></Panel><Panel title="Bearish Example — Sweep Above Resistance" icon={TrendingUp}><img className="luxp-example-chart reverse" src="/trade-setup-breakout.png" alt="Bearish LuxAlgo concept research example"/></Panel></div></main><aside><Panel title="Concept Details" icon={CircleAlert}><dl className="luxp-health-list"><div><dt>Family</dt><dd>{model.selected?.family || "Not supplied"}</dd></div><div><dt>Source</dt><dd>{model.selected?.attribution || "LuxAlgo"}</dd></div><div><dt>Last Synced</dt><dd>{date(model.selected?.last_synced_at)}</dd></div></dl></Panel><Panel title="Compare with Onkar Rules" icon={GitCompareArrows}><Comparison data={model.selected?.comparison}/></Panel></aside></div></div>;
}

function SourceViewer({ model }: { model: LuxPremiumModel }) {
  const sources = model.results.filter((row) => row.source_code_available).slice(0, 20);
  return <div className={cx("luxp-source-layout", model.sourceFullscreen && "fullscreen")}><aside className="luxp-source-list"><h2><Globe2 size={18}/> LuxAlgo Sources</h2><div className="luxp-mini-search"><Search/><input placeholder="Search sources…" value={model.query} onChange={(event) => model.setQuery(event.target.value)}/></div>{sources.map((item) => <button key={item.slug} className={model.source?.indicator_slug === item.slug ? "active" : ""} onClick={() => void model.loadSource(item.slug)}><Code2/><span><strong>{item.name}</strong><small>{item.family || "Public Source"}</small></span><Save size={14}/></button>)}{!sources.length && <EmptyState title="No source imported" body="Public Pine source appears here after synchronization." icon={Code2}/>}</aside><main className="luxp-code"><header><span>{model.source?.name || "Pine source viewer"}</span><div><button onClick={() => model.setSourceFullscreen((value: boolean) => !value)}>{model.sourceFullscreen ? <Square/> : <Maximize2/>}</button>{model.code && <button onClick={() => void navigator.clipboard.writeText(model.code)}><Copy/> Copy Code</button>}</div></header><div className="luxp-code-search"><Search/><input value={model.sourceSearch} onChange={(event) => model.setSourceSearch(event.target.value)} placeholder="Search in code…"/><span>{model.sourceSearch ? `${model.matchingLines} lines` : `${model.codeLines.length} lines`}</span></div>{model.code ? <pre>{model.codeLines.map((line, index) => <code className={model.sourceSearch && line.toLowerCase().includes(model.sourceSearch.toLowerCase()) ? "match" : ""} key={index}><i>{index + 1}</i>{line}{"\n"}</code>)}</pre> : <EmptyState title="Select a source file" body="Imported public source code is read-only and is never executed." icon={Braces}/>}<footer><StatusPill tone="green" icon={ShieldCheck}>Read-only research</StatusPill><span>UTF-8 · Pine Script</span></footer></main><aside className="luxp-source-details"><Panel title="Source Details" icon={Code2}><dl className="luxp-health-list"><div><dt>Name</dt><dd>{model.source?.name || "—"}</dd></div><div><dt>Attribution</dt><dd>{model.source?.attribution || "LuxAlgo"}</dd></div><div><dt>License</dt><dd>{model.source?.license_identifier || model.source?.license_url || "Not supplied"}</dd></div><div><dt>Last Synced</dt><dd>{date(model.source?.last_synced_at)}</dd></div></dl></Panel><div className="luxp-warning"><TriangleAlert/><span><strong>Research reference only</strong>Never execute imported source automatically.</span></div></aside></div>;
}

function EdgeStats({ model }: { model: LuxPremiumModel }) {
  const report = model.edge.report || {};
  const chart = array(report.sessions || report.rows || report.data).map((row) => ({ name: row.session || row.name || row.label, rate: number(row.win_rate || row.winFrequency || row.value), sample: number(row.sample_size || row.sampleSize || row.count) }));
  const data = chart.length ? chart : sessionFallback;
  return <div className="luxp-stack"><div className="luxp-metrics six"><Metric icon={Database} value={report.sample_size || "—"} label="Sample Size"/><Metric icon={Gauge} value={report.win_frequency ? `${report.win_frequency}%` : "—"} label="Win Frequency" tone="cyan"/><Metric icon={Activity} value={report.coverage ? `${report.coverage}%` : "—"} label="Coverage"/><Metric icon={TrendingUp} value={report.confidence_interval || "—"} label="Confidence Interval" tone="violet"/><Metric icon={Clock3} value={report.sessions?.length || "—"} label="Sessions"/><Metric icon={Layers3} value={model.edge.presets.length || "—"} label="Setups Tracked"/></div><div className="luxp-edge-grid"><Panel title="Setup Performance by Session" icon={BarChart3} className="luxp-edge-chart">{data.length ? <ResponsiveContainer width="100%" height={270}><BarChart data={data}><CartesianGrid stroke="#102a47" vertical={false}/><XAxis dataKey="name" stroke="#67809f"/><YAxis stroke="#67809f"/><Tooltip contentStyle={{ background: "#071526", border: "1px solid #1b4b78" }}/><Bar dataKey="rate" fill="#168df5" radius={[5,5,0,0]}/><Line dataKey="sample" stroke="#35d3ae"/></BarChart></ResponsiveContainer> : <EmptyState title="Select an Edge Stats report" body="Choose an official preset and covered symbol to load actual LuxAlgo statistics." icon={Activity}/>}</Panel><Panel title="Filters" icon={Filter} className="luxp-edge-filter"><label>Preset<select id="lux-edge-preset"><option value="">Select concept</option>{model.edge.presets.map((preset: Json) => <option key={preset.id} value={preset.id}>{preset.title || preset.name}</option>)}</select></label><label>Symbol<select onChange={(event) => { const preset = (document.getElementById("lux-edge-preset") as HTMLSelectElement | null)?.value; if (preset && event.target.value) void model.edgeReport(preset, event.target.value); }}><option value="">Select symbol</option>{model.edge.symbols.map((symbol: Json) => <option key={symbol.symbol} value={symbol.symbol}>{symbol.symbol}</option>)}</select></label><button className="primary"><RefreshCw/> Load Official Report</button></Panel><Panel title="About LuxAlgo Edge Stats" icon={CircleAlert}><p>Historical and statistical LuxAlgo research remains separate from live OnkarTradeX signals.</p><div className="luxp-warning"><TriangleAlert/><span>Historical edge builds insight. Your discipline turns it into results.</span></div></Panel></div><Panel title="Concept / Setup Performance" icon={Layers3}>{data.length ? <div className="luxp-performance-table">{data.map((row) => <div key={row.name}><strong>{row.name}</strong><span>{row.sample.toLocaleString()} samples</span><b>{row.rate}%</b><i style={{ width: `${Math.min(100, row.rate)}%` }}/></div>)}</div> : <EmptyState title="No statistical rows loaded" body="Actual MCP Edge Stats will populate this table after a report is selected."/>}</Panel></div>;
}

function SavedResearch({ model }: { model: LuxPremiumModel }) {
  const [active, setActive] = useState<Json | null>(model.saved[0] || null);
  useEffect(() => { if (!active && model.saved.length) setActive(model.saved[0]); }, [active, model.saved]);
  return <div className="luxp-stack"><div className="luxp-metrics four"><Metric icon={BookMarked} value={model.saved.length} label="Saved Concepts"/><Metric icon={ShieldCheck} value="—" label="Onkar Setups" helper="Compared on demand"/><Metric icon={GitCompareArrows} value="—" label="Comparisons" helper="Rule-safe research"/><Metric icon={Wifi} value={model.status === "CONNECTED" ? "100%" : "—"} label="Synced with LuxAlgo" tone="cyan"/></div><div className="luxp-saved-layout"><Panel title="My Saved Research" icon={BookMarked}><div className="luxp-mini-search"><Search/><input placeholder="Search saved research…"/></div><div className="luxp-saved-list">{model.saved.map((item) => <button key={item.id} className={active?.id === item.id ? "active" : ""} onClick={() => { setActive(item); void model.openItem({ slug: item.external_id, kind: item.item_type?.toLowerCase() }); }}><Sparkline/><span><strong>{item.name}</strong><small>{item.family || item.item_type}</small></span><em>{date(item.last_synced_at)}</em></button>)}</div>{!model.saved.length && <EmptyState title="No saved research" body="Save concepts and indicators from the LuxAlgo Library."/>}</Panel><Panel title={active?.name || "Selected Research"} icon={BookOpen} className="luxp-saved-focus">{model.selected ? <ResearchDetail model={model}/> : <EmptyState title="Choose saved research" body="Select an item to review its synchronized content."/>}</Panel><div className="luxp-side-stack"><Panel title="Compare with Onkar Rules" icon={GitCompareArrows}><Comparison data={model.selected?.comparison}/></Panel><Panel title="Recent Uses by Master AI" icon={Bot}><p>LuxAlgo references are labeled <b>LUXALGO_REFERENCE</b> and remain separate from live market evidence.</p><button className="primary" onClick={() => model.onAskMaster("Review my saved LuxAlgo research as LUXALGO_REFERENCE only.")}><Sparkles/> Ask Master AI</button></Panel></div></div></div>;
}

function SettingsView({ model }: { model: LuxPremiumModel }) {
  const connections = [["LuxAlgo MCP", "Research & Indicators", TestTube2, model.status],["MT5", "Trading Platform", TrendingUp, "CONNECTED"],["Twelve Data", "Market Data", BarChart3, "CONNECTED"],["Supabase", "Database", Database, "CONNECTED"],["Master AI", "AI Orchestrator", Bot, "CONNECTED"]] as const;
  const toggles = [["enabled","Enable LuxAlgo MCP"],["cache_enabled","Enable Local Cache"],["edge_stats_enabled","Edge Stats Enabled"],["allow_master_ai","Allow Master AI Access"],["allow_trend_ai","Allow Trend AI Access"],["allow_zone_ai","Allow Zone AI Access"],["allow_setup_ai","Allow Setup AI Access"],["allow_backtest_ai","Allow Backtest AI Access"],["allow_insight_ai","Allow Insight AI Access"],["saved_research_enabled","Saved Research Enabled"]];
  return <div className="luxp-stack"><div className="luxp-connections">{connections.map(([name, subtitle, Icon, state]) => <article key={name} className={name === "LuxAlgo MCP" ? "active" : ""}><span className="luxp-icon"><Icon size={24}/></span><StatusPill tone={state === "CONNECTED" ? "green" : "red"}>{state}</StatusPill><h3>{name}</h3><p>{subtitle}</p></article>)}</div><div className="luxp-settings-grid"><Panel title="LuxAlgo MCP Connection" icon={Link2}><dl className="luxp-connection-data"><div><dt>Status</dt><dd><StatusPill tone={model.status === "CONNECTED" ? "green" : "red"}>{model.status}</StatusPill></dd></div><div><dt>Endpoint</dt><dd>https://mcp.luxalgo.com/mcp</dd></div><div><dt>Authentication</dt><dd>Public Library tools</dd></div><div><dt>Available Tools</dt><dd>{model.health?.availableTools?.length ?? model.health?.available_tools ?? "—"}</dd></div><div><dt>Cache State</dt><dd>{model.settings.cache_enabled !== false ? "Active" : "Disabled"}</dd></div><div><dt>Last Request</dt><dd>{date(model.health?.lastSuccessfulRequest || model.health?.last_successful_request)}</dd></div></dl><button className="primary" onClick={() => void model.loadShell()}><RefreshCw/> Test Connection</button></Panel><div className="luxp-side-stack"><div className="luxp-warning research"><TriangleAlert/><span><strong>Research Only — No Trade Execution</strong>LuxAlgo cannot execute trades, place orders, or override Onkar risk controls.</span></div><Panel title="Connection States" icon={CircleAlert}><div className="luxp-state-list"><StatusPill tone="green">Connected</StatusPill><StatusPill tone="amber">Degraded</StatusPill><StatusPill tone="red">Disconnected</StatusPill><StatusPill tone="violet">Auth Required</StatusPill></div></Panel></div></div><Panel title="LuxAlgo MCP Settings" icon={Settings2}><div className="luxp-toggle-grid">{toggles.map(([key,label]) => <label key={key}><span><b>{label}</b><small>Control isolated research access</small></span><input type="checkbox" checked={model.settings[key] !== false} onChange={(event) => void model.updateSettings({ ...model.settings, [key]: event.target.checked })}/></label>)}</div></Panel></div>;
}

function SyncStatus({ model }: { model: LuxPremiumModel }) {
  const cards = [["Families", model.database.families, model.syncCounters.families],["Concepts", model.database.concepts, model.syncCounters.conceptDetails],["Indicators", model.database.indicators, model.syncCounters.indicatorDetails],["Tags", model.database.tags, model.syncCounters.tags],["Source Files", model.database.sourceFiles, model.syncCounters.sourceFiles],["Failed", model.sync?.failed_items?.length, null],["Retry Queue", model.sync?.retry_queue?.length, null]];
  return <Panel title={`${model.sync?.status || "IDLE"} · ${model.sync?.stage || "READY"}`} eyebrow="RESUMABLE LIBRARY IMPORT" icon={RefreshCw}><div className="luxp-sync-actions"><button disabled={model.syncRunning} onClick={() => void model.startSync("FULL")}>Start Full Sync</button><button disabled={model.syncRunning} onClick={() => void model.startSync("CHANGES")}>Sync Changes Only</button><button className="primary" disabled={model.syncRunning || !model.sync?.job_id || model.sync?.stage === "COMPLETE"} onClick={() => void model.resumeSync()}>Resume Sync</button><button disabled={model.syncRunning || !model.sync?.retry_queue?.length} onClick={() => void model.retrySync()}>Retry Failed Items</button><button className="danger" disabled={!model.syncRunning} onClick={() => void model.cancelSync()}>Cancel</button></div><div className="luxp-sync-cards">{cards.map(([label,value,processed]) => <article key={String(label)}><span>{label}</span><strong>{value ?? 0}</strong>{processed !== null && <small>{processed ?? 0} processed</small>}</article>)}</div>{model.sync?.last_error && <div className="luxp-warning"><TriangleAlert/><span><strong>Latest sync message</strong>{model.sync.last_error}</span></div>}<div className="luxp-failures">{array(model.sync?.failed_items).slice(0, 30).map((item, index) => <article key={`${item.type}-${item.id}-${index}`}><strong>{item.type} · {item.id}</strong><span>{item.error}</span></article>)}</div></Panel>;
}

export function LuxAlgoPremiumView({ model }: { model: LuxPremiumModel }) {
  const [railOpen, setRailOpen] = useState(false);
  const title = model.tab === "SETTINGS" ? "Connections & Settings" : model.tab === "OVERVIEW" ? "LuxAlgo Research Center" : model.tab.replace(" / ", " & ");
  const subtitle = model.tab === "EDGE STATS" ? "Historical performance and statistical research" : model.tab === "SOURCE CODE" ? "View public Pine source as read-only research" : model.tab === "SETTINGS" ? "Connect research, data, AI modules and infrastructure" : "Institutional knowledge, synchronized for OnkarTradeX research";
  const content = model.tab === "OVERVIEW" ? <Overview model={model}/> : model.tab === "LIBRARY" ? <Library model={model}/> : model.tab === "INDICATORS" ? <Library model={model} indicator/> : model.tab === "SOURCE CODE" ? <SourceViewer model={model}/> : model.tab === "EDGE STATS" ? <EdgeStats model={model}/> : model.tab === "SAVED RESEARCH" ? <SavedResearch model={model}/> : model.tab === "SETTINGS" ? <SettingsView model={model}/> : model.tab === "SYNC STATUS" ? <SyncStatus model={model}/> : <PriceAction model={model}/>;
  return <section className="luxp-shell"><aside className={cx("luxp-rail", railOpen && "open")}><button className="luxp-logo" onClick={model.onBack}><img src="/onkar-tradex-logo.png" alt="OnkarTradeX"/><span><strong>OnkarTradeX</strong><small>TRADE SMARTER · HIGHER</small></span></button><nav>{researchTabs.map(({ tab, label, icon: Icon }) => <button key={tab} className={model.tab === tab ? "active" : ""} onClick={() => { model.setTab(tab); model.setSelected(null); setRailOpen(false); }}><Icon size={18}/><span>{label}</span></button>)}</nav><div className="luxp-rail-note">Research.<br/>Rules.<br/><b>Real Results.</b></div></aside><main className="luxp-workspace"><div className="luxp-topbar"><button className="luxp-menu" onClick={() => setRailOpen((value) => !value)}><Menu/></button><div className="luxp-global-search"><Search/><input placeholder="Search markets, symbols, or anything…"/><kbd>⌘ K</kbd></div><button><Bell/></button><span className="luxp-avatar">T</span><div className="luxp-user"><b>Trade Smarter</b><small>Every Day</small></div></div><header className="luxp-pagehead"><span className="luxp-pageicon"><TestTube2/></span><div><h1>{title.split(" ").map((word, index) => index === title.split(" ").length - 1 ? <em key={word}>{word}</em> : `${word} `)}</h1><p>{subtitle}</p></div><div className="luxp-head-status"><StatusPill tone={model.status === "CONNECTED" ? "green" : "red"}>{model.status === "CONNECTED" ? "MCP Connected" : model.status}</StatusPill><StatusPill tone="blue" icon={Database}>Cache Active</StatusPill><StatusPill tone="violet" icon={Sparkles}>Research Only</StatusPill></div></header>{model.error && <div className="luxp-error"><TriangleAlert/><span><strong>LuxAlgo Research Temporarily Unavailable</strong>{model.error}</span><button onClick={() => model.setError("")}><X/></button></div>}{model.loading && <div className="luxp-loading"><RefreshCw/> Loading synchronized LuxAlgo research…</div>}<div className="luxp-content">{content}</div></main></section>;
}
